/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as WriteRouteImport } from './routes/write'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiAssistRouteImport } from './routes/api/assist'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistRoute = ApiAssistRouteImport.update({
  id: '/api/assist',
  path: '/api/assist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/write': typeof WriteRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/assist': typeof ApiAssistRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/write': typeof WriteRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/assist': typeof ApiAssistRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/write': typeof WriteRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/assist': typeof ApiAssistRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/write'
    | '/api/analyze'
    | '/api/assist'
    | '/api/generate-image'
    | '/api/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/write'
    | '/api/analyze'
    | '/api/assist'
    | '/api/generate-image'
    | '/api/transcribe'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/write'
    | '/api/analyze'
    | '/api/assist'
    | '/api/generate-image'
    | '/api/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  WriteRoute: typeof WriteRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiAssistRoute: typeof ApiAssistRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assist': {
      id: '/api/assist'
      path: '/api/assist'
      fullPath: '/api/assist'
      preLoaderRoute: typeof ApiAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  WriteRoute: WriteRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiAssistRoute: ApiAssistRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
